pool:
  name: MacNetCorePools
  demands: npm

steps:
- task: VersionExtractor@4
  name: versionExtractor
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(build.buildNumber)'

- task: TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: Npm@1
  displayName: 'Install TypeScript'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g typescript'

- task: Npm@1
  displayName: 'Publish GetAzureAdApplicationId'
  inputs:
    command: custom
    workingDir: GetAzureAdApplicationId
    verbose: false
    customCommand: 'run publishExt'

- task: Npm@1
  displayName: 'Publish ManageAzureAdApplication'
  inputs:
    command: custom
    workingDir: ManageAzureAdApplication
    verbose: false
    customCommand: 'run publishExt'

- task: Npm@1
  displayName: 'Publish RemoveAzureAdApplication'
  inputs:
    command: custom
    workingDir: RemoveAzureAdApplication
    verbose: false
    customCommand: 'run publishExt'

- task: PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: '
  inputs:
    extensionVersion: '$(versionExtractor.fullVersion)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy Files *.vsix'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

